export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const INCREMENT_TO_CART = 'INCREMENT_TO_CART';
export const DECREMENT_TO_CART = 'DECREMENT_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
